
package pl.agh.kis.soa.server.soap.implementations;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import pl.agh.kis.soa.server.soap.interfaces.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DishSoapService", targetNamespace = "http://interfaces.soap.server.soa.kis.agh.pl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DishSoapService {


    /**
     * 
     * @param dishPrice
     * @param dishName
     * @param categoryId
     */
    @WebMethod
    @RequestWrapper(localName = "addDishToCategory", targetNamespace = "http://interfaces.soap.server.soa.kis.agh.pl/", className = "pl.agh.kis.soa.server.soap.interfaces.AddDishToCategory")
    @ResponseWrapper(localName = "addDishToCategoryResponse", targetNamespace = "http://interfaces.soap.server.soa.kis.agh.pl/", className = "pl.agh.kis.soa.server.soap.interfaces.AddDishToCategoryResponse")
    public void addDishToCategory(
        @WebParam(name = "dishName", targetNamespace = "")
        String dishName,
        @WebParam(name = "dishPrice", targetNamespace = "")
        Float dishPrice,
        @WebParam(name = "categoryId", targetNamespace = "")
        Long categoryId);

}
